-- Digital Fitness Coaching Platform
-- Foundation: extensions, schema, shared domains, and helper functions.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS fitness;

SET search_path TO fitness, public;

CREATE TYPE account_status AS ENUM ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DISABLED', 'DELETION_PENDING', 'DELETED');
CREATE TYPE gender_code AS ENUM ('MALE', 'FEMALE', 'NON_BINARY', 'OTHER', 'PREFER_NOT_TO_SAY');
CREATE TYPE verification_status AS ENUM ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED');
CREATE TYPE coaching_relationship_status AS ENUM ('PENDING', 'ACTIVE', 'PAUSED', 'ENDED', 'REJECTED', 'CANCELLED');
CREATE TYPE coaching_mode AS ENUM ('HUMAN_COACH', 'SELF_DIRECTED');
CREATE TYPE lifecycle_status AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ENDED', 'ABANDONED', 'REPLACED', 'ARCHIVED');
CREATE TYPE proposal_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED');
CREATE TYPE proposal_source AS ENUM ('STUDENT', 'TRAINER', 'AI_ASSISTANCE', 'SYSTEM');
CREATE TYPE objective_priority AS ENUM ('PRIMARY', 'SECONDARY');
CREATE TYPE permission_decision AS ENUM ('ALLOW', 'DENY');
CREATE TYPE data_scope_code AS ENUM ('WORKOUT_HISTORY', 'BODY_METRICS', 'PROGRESS_PHOTOS', 'NUTRITION_LOGS', 'AI_RECOMMENDATIONS', 'WORKOUT_PLAN_HISTORY');
CREATE TYPE plan_status AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE plan_source AS ENUM ('STUDENT', 'TRAINER', 'AI_PROPOSAL', 'TEMPLATE');
CREATE TYPE planned_workout_status AS ENUM ('SCHEDULED', 'COMPLETED', 'MISSED', 'SKIPPED', 'RESCHEDULED', 'CANCELLED');
CREATE TYPE actual_workout_status AS ENUM ('IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'ABORTED');
CREATE TYPE set_type AS ENUM ('WARMUP', 'WORKING', 'DROP', 'FAILURE', 'AMRAP', 'COOLDOWN');
CREATE TYPE set_completion_status AS ENUM ('PLANNED', 'COMPLETED', 'SKIPPED', 'FAILED');
CREATE TYPE appointment_status AS ENUM ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'ABSENT', 'RESCHEDULED');
CREATE TYPE request_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED');
CREATE TYPE measurement_value_type AS ENUM ('NUMERIC', 'TEXT', 'BOOLEAN');
CREATE TYPE metric_collection_type AS ENUM ('DIRECT', 'DEVICE_DEPENDENT', 'CALCULATED');
CREATE TYPE measurement_validation_status AS ENUM ('PENDING', 'VALID', 'SUSPECT', 'REJECTED', 'SUPERSEDED');
CREATE TYPE training_activity_state AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE meal_type AS ENUM ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'OTHER');
CREATE TYPE message_type AS ENUM ('TEXT', 'IMAGE', 'FILE', 'WORKOUT_SHARE', 'SCHEDULE_SHARE', 'SYSTEM');
CREATE TYPE message_status AS ENUM ('SENT', 'DELIVERED', 'READ', 'DELETED');
CREATE TYPE notification_channel AS ENUM ('IN_APP', 'PUSH', 'EMAIL');
CREATE TYPE delivery_status AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED');
CREATE TYPE ai_run_status AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'REJECTED_BY_VALIDATOR', 'CANCELLED');
CREATE TYPE recommendation_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'APPLIED', 'EXPIRED', 'CANCELLED');
CREATE TYPE knowledge_status AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE attention_source AS ENUM ('SYSTEM_RULE', 'AI_RECOMMENDATION');
CREATE TYPE attention_status AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED');
CREATE TYPE severity_level AS ENUM ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE payment_status AS ENUM ('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED');
CREATE TYPE subscription_status AS ENUM ('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', 'EXPIRED');
CREATE TYPE report_status AS ENUM ('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED', 'CLOSED');

CREATE DOMAIN percentage_0_100 AS numeric(7,4)
    CHECK (VALUE >= 0 AND VALUE <= 100);

CREATE DOMAIN nonnegative_numeric AS numeric(18,6)
    CHECK (VALUE >= 0);

CREATE OR REPLACE FUNCTION fitness.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fitness.prevent_update_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$;

