package com.fitnesscoaching.platform.modules.workout.domain;

public enum WorkoutExecutionError {
    WORKOUT_EXECUTION_NOT_FOUND(404), WORKOUT_EXECUTION_ACCESS_DENIED(403),
    WORKOUT_EXECUTION_LIFECYCLE_CONFLICT(409), ACTIVE_WORKOUT_EXECUTION_EXISTS(409),
    WORKOUT_EXECUTION_VERSION_CONFLICT(409), WORKOUT_EXECUTION_IDEMPOTENCY_CONFLICT(409),
    WORKOUT_SET_IDENTITY_CONFLICT(409), PLANNED_WORKOUT_ALREADY_STARTED(409),
    PLANNED_WORKOUT_NOT_STARTABLE(409), PLANNED_WORKOUT_ADJUSTMENTS_SEALED(409),
    PLANNED_WORKOUT_SCHEDULE_LOCKED(409), WORKOUT_EXECUTION_TERMINAL(409),
    WORKOUT_EXECUTION_BASELINE_INVALID(409), VALIDATION_FAILED(400);

    private final int status;
    WorkoutExecutionError(int status) { this.status = status; }
    public int status() { return status; }
}
