package com.fitnesscoaching.platform.modules.workout.domain;

public enum WorkoutPlanError {
    WORKOUT_PLAN_NOT_FOUND(404), WORKOUT_PLAN_VERSION_NOT_FOUND(404), PLANNED_WORKOUT_NOT_FOUND(404),
    WORKOUT_PLAN_ACCESS_DENIED(403), COACHING_PERIOD_REQUIRED(403),
    WORKOUT_PLAN_LIFECYCLE_CONFLICT(409), ACTIVE_WORKOUT_PLAN_ALREADY_EXISTS(409),
    WORKOUT_PLAN_VERSION_CONFLICT(409), PLANNED_WORKOUT_VERSION_CONFLICT(409),
    WORKOUT_PLAN_IDEMPOTENCY_CONFLICT(409), WORKOUT_PLAN_IMMUTABLE(409),
    WORKOUT_PLAN_SUCCESSOR_REQUIRED(409), WORKOUT_PLAN_EXERCISE_UNAVAILABLE(409),
    WORKOUT_PLAN_EFFECTIVE_TIME_CONFLICT(409), PLANNED_WORKOUT_ALREADY_STARTED(409),
    PLANNED_WORKOUT_NOT_STARTABLE(409), PLANNED_WORKOUT_ADJUSTMENTS_SEALED(409),
    PLANNED_WORKOUT_SCHEDULE_LOCKED(409), VALIDATION_FAILED(400);

    private final int status;
    WorkoutPlanError(int status) { this.status = status; }
    public int status() { return status; }
}
